config/routes.rb
Roommaker::Application.routes.draw do
  get "asks/destroy"
  get "invites/destroy"
  get "welcome/index"
  resources :sessions, :only=> [:new,:create,:destroy]
  resources :users do
    resources :acceptedtasks
    resources :currenttasks
    resources :completedtasks
  end
  resources :pendingtasks
  root "welcome#index"
  get "/users/groups/:user_id"=> "groups#index"
  get "/groups/:user_id/new"=> "groups#new"
  resources :groups

  get "welcome_path" => "welcome#index"
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get '/sessions' => 'sessions#create'
  get '/users/:user_id/:id/yes' => "pendingtasks#yes"
  get '/users/:user_id/:id/no' => "pendingtasks#no"
  get '/users/:user_id/:id/delete' => "currenttasks#delete"
  get "/groups/"=> "groups#index"
  get "/users/:user_id/:id/verifY" => "currenttasks#delete"
  get "/users/:user_id/:id/:not" => "currenttasks#delete"
  get "/:user_id/:id/incomplete" => "currenttasks#incomplete"
  get "groups/:group_id/:user_id/leave" => "groups#leave"
  get "groups/:group_id/invite" => "groups#invite"
  post "/groups/:group_id/invitesearch" => "groups#invitesearch"
  resources :invites, :only=> [:destroy]
  get "groups/:group_id/ask" => "groups#ask"
  get "groups/:group_id/:asker_id" => "groups#join"
  resources :asks, :only=> [:destroy]
  post "/groups/search" => "groups#search"
  

  

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def index
		@groups = Group.all
		
	end

	def search
		@group=Group.find_by_name(params[:group_name])
		@groups=[]
		Group.all.each do |group|
			@groups<<group if group.name[0]==params[:group_name][0]
		end
		
	end

	def leave
		@user=current_user
		@group=Group.find_by_id(params[:group_id])
		@user.groups.delete(@group)
			
		redirect_to "/groups"
	end

	def invite
		@group=Group.find_by_id(params[:group_id])

	end

	def invitesearch
		user=User.find_by_name(params[:name])
		 ingroupalready= user==nil ? true : false
		user.groups.each do |group|
			ingroupalready=true if group.id==params[:group_id].to_i
		end 

		if user!=nil && ingroupalready==false
			#might need invite model which then creates an invite for a user. if they accept invite, join group.
			#have to go user.invites (user has many invites and invites belong to user) on their welcome page, 
			user.invites << Invite.new({:creator_id=>current_user.id,
										:group_id=>params[:group_id].to_i
										})
			flash[:notice]= "Invite sent to #{user.name}"
			redirect_to "/welcome/index"
		else
			if user==nil
				flash[:error]= "Could not find person"
			elsif ingroupalready!=[]
				flash[:error]= "Person already belongs to group"
			end
			redirect_to "/groups/#{params[:group_id]}/invite"
		end
		#{"utf8"=>"✓", "authenticity_token"=>"ArAqpTPyKlLq+IrQaKBp0VolZM5es511P26L57MHVsY=", 
		#{}"name"=>"sfsfsf", "commit"=>"Invite Friend", "controller"=>"groups", "action"=>"invitesearch", 
		#{}"group_id"=>"12"}
	end

	def new
		@group = Group.new
	end

	def create
		@group = Group.new(group_params)
		useringroup=false
		@user=current_user
		@group.creator_id=current_user.id
		useringroup= true if @user.groups.where(name: @group.name).size>0

		if @group.save && !useringroup
			
			@group.users << @user unless @group.users.include? @user
			redirect_to "/users/#{current_user.id}"
		else
			@group.delete
			flash[:error]= "You already belong to a group with that name!"
			redirect_to new_group_path
		end
	end

	def show
		@group = Group.find(params[:id])
	end

	def join
		@group = Group.find(params[:group_id])
		@user = User.find_by_id(params[:asker_id])

		if @group.save
			@group.users << @user unless @group.users.include? @user
			@user.invites.each do |i|
				i.delete if i.group_id==@group.id
			end
			redirect_to "/users/#{current_user.id}"
		end
	end

	def ask
		#editgrouppathadds to group
		@asker=current_user
		@group=Group.find_by_id(params[:group_id])
		@creator=User.find_by_id(@group.creator_id)
		@creator.asks << Ask.new({:asker_id=>@asker.id,
								  :group_id=>@group.id})
		flash[:notice]="Request to join sent"
		redirect_to current_user
	end

	def edit
		@group = Group.find(params[:id])
		@user = current_user

		if @group.save
			@group.users << @user unless @group.users.include? @user
			@user.invites.each do |i|
				i.delete if i.group_id==@group.id
			end
			redirect_to "/users/#{current_user.id}"
		end
	end

	def update 
		@group = Group.find(params[:id])
		@user = current_user


		if @group.update_attributes(group_params)
			@group.users << @user unless @group.users.include? @user
			redirect_to "/users/#{current_user.id}"
		else
			render :edit
		end
	end

	def delete
		@group = Group.find(params[:id])
		@group.destroy
		redirect_to current_user
	end

	private
	def group_params
		params.require(:group).permit(:name, :creator_id)
	end
end

app/helpers/groups_helper.rb
module GroupsHelper
	def themost(group)
		max=0
		maxuser="bob"
 		group.users.each do |u| 
     		usertotal=0 
     		u.completedtasks.each do |ct|
        		if ct.group == group.name
           			usertotal+=1 if u.id==ct.completer_id
        		end
        	end
        	if usertotal>=max
        		max=usertotal 
        		maxuser=u
        	end
		end
		return maxuser

	end

	def theleast(group)
		min=10000
		minuser=nil
		unless group.users.size==1

 			group.users.each do |u| 
     			usertotal=0 
     			u.completedtasks.each do |ct|
        			if ct.group == group.name
           				usertotal+=1 if u.id==ct.completer_id
        			end
        		end
        		if usertotal<=min
        			min=usertotal 
        			minuser=u
        		end
			end
		end
		return minuser
	end


	def mostrecent(group)
		min=0
		minuser=nil
		minid=-1
 		group.users.each do |u| 
     		usertotal=0 
     		u.completedtasks.each do |ct|
        		if ct.group == group.name

        			if min==0 || ct.created_at > min
    
        				min=ct.created_at
        				minid=ct.id

        				minuser=u

        			end
        		end
        	end
        	answer=[minuser,minid]

        	return answer
		end

		
	end

	def leastrecent(group)
		val=[]
		group.users.each do |u|
			val << u.completedtasks.where(group: group.name).first unless u.completedtasks.where(group: group.name).first==nil
		end


		answer=[val.min_by{ |x| x.id }.user_id, val.min_by{ |x| x.id }]
		return answer
	end

	def never(group)
		val={}
		group.users.each do |u|
			val[u]= u.completedtasks.where(group: group.name).first
		end
		
		answer=val.select{|c| val[c]==nil}

		
		return answer
	end
end

app/views/groups/edit.html.erb
<%= form_for @group do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.submit %>
<% end %>

app/views/groups/index.html.erb
<%= form_tag "/groups/search" do %>
  Search for 
   <%= label_tag :group_name %>
      <%= text_field_tag :group_name, params[:group_name] %>
  <%= submit_tag("Search") %>
<% end %>

<% @groups.each do |group| %>
  <%= group.name %> Size: <%= group.users.size %> <%= "Group Creator: "+ User.find_by_id(group.creator_id).name unless group.creator_id==nil %>
  <% if current_user.id==group.creator_id %>
  	<%= link_to "Invite memebers", "groups/#{group.id}/invite" %>
  <% end %>
  <% if current_user.groups.include?(group) %>
  	<%= link_to "Leave", "groups/#{group.id}/#{current_user.id}/leave" %>
  <% else %>
  	<%= link_to "Ask to Join", "/groups/#{group.id}/ask" %>
  <% end %>

   <br>
   

<% end %>

app/views/groups/invite.html.erb
<%= form_tag "/groups/#{@group.id}/invitesearch" do %>
	Who do you want to invite to <%= @group.name %>
	 <%= label_tag :name %>
      <%= text_field_tag :name, params[:name] %>
	<%= submit_tag("Invite Friend") %>
<% end %>

app/views/groups/new.html.erb
<%= form_for @group do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.submit %>
<% end %>

app/views/groups/search.html.erb
Your result returned with <%= @group==nil ? "Nothing!" : @group.name %>
<% if @group!=nil %>
<% if current_user.groups.include?(@group) %>
  	<%= link_to "Leave", "groups/#{@group.id}/#{current_user.id}/leave" %><br>
  <% else %>
  	<%= link_to "Ask to Join", "/groups/#{@group.id}/ask" %><br>
<% end %>
<% end %>
Did you mean any of these?:
<% @groups.each do |group| %>
	<% if current_user.groups.include?(group) %>
  	<%= link_to "Leave #{group.name}", "groups/#{group.id}/#{current_user.id}/leave" %><br>
  <% else %>
  	<%= link_to "Ask to Join", "/groups/#{group.id}/ask" %><br>
<% end %>
<% end %>

<%= link_to "Back to Groups and Search", groups_path %>

app/views/groups/show.html.erb
<%= @group.name %><br>
Number of Tasks completed: <br>
<% @group.users.each do |u| %>
     <%= u.name %>: 
     <% usertotal=0 %>
     <% u.completedtasks.each do |ct| %>
        <% if ct.group == @group.name %>
           <% usertotal+=1 if u.id==ct.completer_id %>

        <% end %>
     <%end %>
     <%= usertotal  %> <br>

  <% end %>

<% if !(@group.users.size<=1) %>
  Who has done the most: <%= themost(@group).name %><br>
  Who has done the least: <%= theleast(@group).name %><br>

  Who has done the most recent task: <%= mostrecent(@group)[0]==nil ? "Your network is too small" : mostrecent(@group)[0].name %> with <%= Completedtask.find_by_id(mostrecent(@group)[1])==nil ? "no tasks" : Completedtask.find_by_id(mostrecent(@group)[1]).text %> at <%= Completedtask.find_by_id(mostrecent(@group)[1])==nil ? "none created" : Completedtask.find_by_id(mostrecent(@group)[1]).created_at %><br>

  Who has not done a task in the longest time: 
  <% unless (leastrecent(@group))==nil %>
  <%= User.find_by_id(leastrecent(@group)[0]).name %> at <%= leastrecent(@group)[1].created_at %><br>
  Who has never done anything: <div style="display: inline"><% never(@group).keys.each do |val| %>
  									<%= val.name %>
  									<% if never(@group).keys.size>1 && val!=never(@group).keys.last %>
  										<%= "and" %>
  									<% end %>
  								<% end %></div>
<% end %>

<% else %>
  <%= "Get a larger network!" %>

<% end %>