config/routes.rb
Roommaker::Application.routes.draw do
  get "asks/destroy"
  get "invites/destroy"
  get "welcome/index"
  resources :sessions, :only=> [:new,:create,:destroy]
  resources :users do
    resources :acceptedtasks
    resources :currenttasks
    resources :completedtasks
  end
  resources :pendingtasks
  root "welcome#index"
  get "/users/groups/:user_id"=> "groups#index"
  get "/groups/:user_id/new"=> "groups#new"
  resources :groups

  get "welcome_path" => "welcome#index"
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get '/sessions' => 'sessions#create'
  get '/users/:user_id/:id/yes' => "pendingtasks#yes"
  get '/users/:user_id/:id/no' => "pendingtasks#no"
  get '/users/:user_id/:id/delete' => "currenttasks#delete"
  get "/groups/"=> "groups#index"
  get "/users/:user_id/:id/verifY" => "currenttasks#delete"
  get "/users/:user_id/:id/:not" => "currenttasks#delete"
  get "/:user_id/:id/incomplete" => "currenttasks#incomplete"
  get "groups/:group_id/:user_id/leave" => "groups#leave"
  get "groups/:group_id/invite" => "groups#invite"
  post "/groups/:group_id/invitesearch" => "groups#invitesearch"
  resources :invites, :only=> [:destroy]
  get "groups/:group_id/ask" => "groups#ask"
  get "groups/:group_id/:asker_id" => "groups#join"
  resources :asks, :only=> [:destroy]
  post "/groups/search" => "groups#search"
  

  

end

app/models/acceptedtask.rb
class Acceptedtask < ActiveRecord::Base
	belongs_to :user
end

app/models/ask.rb
class Ask < ActiveRecord::Base
	belongs_to :user
end

app/models/completedtask.rb
class Completedtask < ActiveRecord::Base
	belongs_to :user
end

app/models/currenttask.rb
class Currenttask < ActiveRecord::Base
	belongs_to :user

	def verified?
		self.verifed>0
	end
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/incompletetask.rb
class Incompletetask < ActiveRecord::Base
	belongs_to :user
end

app/models/invite.rb
class Invite < ActiveRecord::Base
	belongs_to :user
end

app/models/no.rb
class No < ActiveRecord::Base
	belongs_to :pendingtask
	belongs_to :user
end

app/models/nod.rb
class Nod < ActiveRecord::Base
	belongs_to :pendingtask
	belongs_to :user
end

app/models/pendingtask.rb
class Pendingtask < ActiveRecord::Base
	has_and_belongs_to_many :users
	validates :assignee_id, :text, presence: true
	has_many :pendingvotes
	has_many :nods
	has_many :nos
end

app/models/pendingvote.rb
class Pendingvote < ActiveRecord::Base
	belongs_to :pendingtask
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
  has_and_belongs_to_many :pendingtasks
  has_many :acceptedtasks
  has_many :currenttasks
  has_many :completedtasks
  has_and_belongs_to_many :groups
  has_many :nods
  has_many :nos
  has_many :incompletetasks
  has_many :invites
  has_many :asks
  
	def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.password="cat"
      user.password_confirmation="cat"
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def self.addpending(id, pendingtask)
    User.find_by_id(id).pendingtasks.create!(pendingtask)
  end


end

app/models/yes.rb
class Yes < ActiveRecord::Base
	belongs_to :pendingtask
	
end

app/controllers/asks_controller.rb
class AsksController < ApplicationController
 def destroy
  	@ask = Ask.find(params[:id])
	@ask.destroy
	redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :delete_tasks

  def new
  	@user=User.new
  end

  def create
  	@user=User.new(user_params)
  	if @user.save
  		redirect_to "/welcome_path", :notice => "Signed up!"
  	else
      
  		render "new"
  	end
  end

   def show

		@user=User.find(params[:id])

    @pendingtasks=Pendingtask.all

    
		session[:user_id]=@user.id
    @acceptedtasks = @user.acceptedtasks
    @currenttasks= @user.currenttasks
    @completedtasks = @user.completedtasks
    @groups=@user.groups
    @nods=@user.nods
    @nos=@user.nos
    @incompletetasks=@user.incompletetasks
    def selectmax(pendingtasks,acceptedtasks,completedtasks,currenttasks,incompletetasks)
      arr=[pendingtasks,acceptedtasks,completedtasks,currenttasks,incompletetasks]
      return arr.max_by {|x| x.size }
    end
    @large=selectmax(@pendingtasks,@acceptedtasks,@completedtasks,@currenttasks,@incompletetasks).size
    @grouptasks={}
    @user.groups.each do |group|
      val||=[]
      val <<@user.pendingtasks.where(group: group.name)
      val <<@user.acceptedtasks.where(group: group.name)
      val << @user.currenttasks.where(group: group.name)
      val << @user.completedtasks.where(group: group.name)
      val <<@user.incompletetasks.where(group: group.name)
      @grouptasks[group]=val
    end





	end

  private
  def user_params
  	params.require(:user).permit(:email,:password, :password_confirmation, :name)
  end

  def delete_tasks
    unless current_user==nil
    @currentguy=User.find_by_id(current_user.id)
    @result={}
    @pendingtasks=Pendingtask.all
    @pendingtasks.each do |task|
      @totalyes=task.nods.size
      @totalno=task.nos.size
      @result[task.id] = [@totalyes,@totalno]
      unless @result[task.id]==nil
        if @result[task.id][-1] >= -1*task.negthreshold
          task.destroy
        end
        if @result[task.id][0] >= task.threshold
          assigned = task.assignee_id.to_i
          @user = User.find_by_id(assigned)

          @user.currenttasks.create!({text: task[:text],
                                      group: task[:group],
                                      completer_id:@user.id,
                                      verified: 0}) unless @user.currenttasks.include? Currenttask.find_by_text(task[:text]) || @user==nil

          votingids = task.voter_ids.split(" ")
          votingids.each do |id|
            @user=User.find_by_id(id)
            if @user.id!=task.assignee_id.to_i
              @user.acceptedtasks.create!({text: task[:text], group: task[:group], completer_id: task[:assignee_id]}) unless @user.acceptedtasks.include? Acceptedtask.find_by_text(task[:text])
            end 
 
          end
        
          task.destroy
        end
      end
    end
  end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def selectmax(pendingtasks,acceptedtasks,completedtasks,currenttasks,incompletetasks)
      arr=[pendingtasks,acceptedtasks,completedtasks,currenttasks,incompletetasks]
      return arr.max_by {|x| x.size }.size
    end
end

app/helpers/asks_helper.rb
module AsksHelper
end

app/helpers/currenttasks_helper.rb
module CurrenttasksHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
	def themost(group)
		max=0
		maxuser="bob"
 		group.users.each do |u| 
     		usertotal=0 
     		u.completedtasks.each do |ct|
        		if ct.group == group.name
           			usertotal+=1 if u.id==ct.completer_id
        		end
        	end
        	if usertotal>=max
        		max=usertotal 
        		maxuser=u
        	end
		end
		return maxuser

	end

	def theleast(group)
		min=10000
		minuser=nil
		unless group.users.size==1

 			group.users.each do |u| 
     			usertotal=0 
     			u.completedtasks.each do |ct|
        			if ct.group == group.name
           				usertotal+=1 if u.id==ct.completer_id
        			end
        		end
        		if usertotal<=min
        			min=usertotal 
        			minuser=u
        		end
			end
		end
		return minuser
	end


	def mostrecent(group)
		min=0
		minuser=nil
		minid=-1
 		group.users.each do |u| 
     		usertotal=0 
     		u.completedtasks.each do |ct|
        		if ct.group == group.name

        			if min==0 || ct.created_at > min
    
        				min=ct.created_at
        				minid=ct.id

        				minuser=u

        			end
        		end
        	end
        	answer=[minuser,minid]

        	return answer
		end

		
	end

	def leastrecent(group)
		val=[]
		group.users.each do |u|
			val << u.completedtasks.where(group: group.name).first unless u.completedtasks.where(group: group.name).first==nil
		end


		answer=[val.min_by{ |x| x.id }.user_id, val.min_by{ |x| x.id }]
		return answer
	end

	def never(group)
		val={}
		group.users.each do |u|
			val[u]= u.completedtasks.where(group: group.name).first
		end
		
		answer=val.select{|c| val[c]==nil}

		
		return answer
	end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

<%= link_to "Home", root_url %>

app/views/users/show.html.erb
<% @grouptasks.keys.each do |task| %>
<table>
<thead>
  <tr>
    <th colspan="2"> Location: <%= task.name %> </th>
    <th colspan="2"> <%= link_to "New Pending Task", new_pendingtask_path %></th>
    <th colspan="2"> <%= link_to "Location Stats", group_path(task) %> </th>
  </tr>
<tr>
  <th>Pending Tasks</th> <!-- status of pending, accepted, current -->
  <th>Accepted Tasks</th>
  <th>Current Tasks</th>
  <th>Completed Tasks</th>
  <th>Incompleted Tasks</th>
</tr>
</thead>
<tbody>
  
  <% supcount=0 %>
  <% @grouptasks[task].each do |val| %>

  <% while supcount < selectmax(@grouptasks[task][0],@grouptasks[task][1],@grouptasks[task][2],@grouptasks[task][3],@grouptasks[task][4]) %>
  <% count=0 %>

  <tr>
    <td>
      <% unless @grouptasks[task][count][supcount]==nil%>
      <%= current_user==User.find_by_id(@grouptasks[task][count][supcount].assignee_id) ? "You have" : User.find_by_id(@grouptasks[task][count][supcount].assignee_id).name + " has"%> to <%= @grouptasks[task][count][supcount].text%> <br>
      <% if current_user.id == @grouptasks[task][count][supcount].filler_id%>

    <%= link_to "Delete Task", pendingtask_path(@grouptasks[task][count][supcount].id), :confirm => "Delete?", :method => :delete %>
  <% end %> <%= @grouptasks[task][count][supcount].nods.size %> vs.    <%= @grouptasks[task][count][supcount].nos.size %> | Needs <%= @grouptasks[task][count][supcount].threshold %> votes<br> <% if (@user.nods.where(pendingtask_id: @grouptasks[task][count][supcount].id).size)==0 %>
    Vote <%= link_to "Yes", "/users/#{@user.id}/#{@grouptasks[task][count][supcount].id}/yes" %> or
  <% end %>
  <% if (@user.nos.where(pendingtask_id: @grouptasks[task][count][supcount].id).size)==0%>
    Vote <%= link_to "No", "/users/#{@user.id}/#{@grouptasks[task][count][supcount].id}/no" %>
  <% end %><% end %> </td>
    <% count+=1 %>
    <td>
      <% unless @grouptasks[task][count][supcount]==nil %>
      <%= current_user==User.find_by_id(@grouptasks[task][count][supcount].completer_id) ? "You have" : User.find_by_id(@grouptasks[task][count][supcount].completer_id).name + " has" %>  to  
      <%= @grouptasks[task][count][supcount].text %>
      <% Currenttask.all.each do |cask| %>

    <% if cask.verified>=1 %>
      <% if cask.text==@grouptasks[task][count][supcount].text && cask.completer_id==@grouptasks[task][count][supcount].completer_id %><br>
        <%= link_to "Verify Task's completion", "/users/#{cask.completer_id}/#{cask.id}/verifY" %> <br> 

        <%= link_to "Verify Not completed", "/users/#{cask.completer_id}/#{cask.id}/not" %> <br> 
      <% end %>
    <% end %>
  <% end %> 
      <% end %> </td>
    <% count+=1 %>
    <td>
      <% unless @grouptasks[task][count][supcount]==nil %>
      <%= current_user==User.find_by_id(@grouptasks[task][count][supcount].completer_id) ? "You have" : User.find_by_id(@grouptasks[task][count][supcount].completer_id).name + " has"%>  to <%= @grouptasks[task][count][supcount].text %><br>
      <% if @grouptasks[task][count][supcount].verified!=1 %>

    <%= link_to "Complete?", "/users/#{@grouptasks[task][count][supcount].completer_id}/#{@grouptasks[task][count][supcount].id}/delete" %> <br>
    <%= link_to "Not going to do it?", "/#{@grouptasks[task][count][supcount].completer_id}/#{@grouptasks[task][count][supcount].id}/incomplete" %> <br>
  <% end %>
  <% if @grouptasks[task][count][supcount].verified==1 %>
    <%= "Waiting for verification".upcase %><br>
  <% end %> 
      <% end %> </td>
    <% count+=1 %>
    <td>
      <% unless @grouptasks[task][count][supcount]==nil %>
      <%= User.find_by_id(@grouptasks[task][count][supcount].completer_id).name %> did <%= @grouptasks[task][count][supcount].text %> 
      <% end %> </td>
    <% count+=1 %>
    <td>
      <% unless @grouptasks[task][count][supcount]==nil %>
      <%= User.find_by_id(@grouptasks[task][count][supcount].completer_id).name %> did not <%= @grouptasks[task][count][supcount].text %> 
      <% end %> </td>
    <% count+=1 %>

<!--incompletetask-->
  </tr>
  <% supcount+=1 %>
<% end %>
  <% end %>
</tbody>
</table>

<% end %>
   