config/routes.rb
Roommaker::Application.routes.draw do
  get "asks/destroy"
  get "invites/destroy"
  get "welcome/index"
  resources :sessions, :only=> [:new,:create,:destroy]
  resources :users do
    resources :acceptedtasks
    resources :currenttasks
    resources :completedtasks
  end
  resources :pendingtasks
  root "welcome#index"
  get "/users/groups/:user_id"=> "groups#index"
  get "/groups/:user_id/new"=> "groups#new"
  resources :groups

  get "welcome_path" => "welcome#index"
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get '/sessions' => 'sessions#create'
  get '/users/:user_id/:id/yes' => "pendingtasks#yes"
  get '/users/:user_id/:id/no' => "pendingtasks#no"
  get '/users/:user_id/:id/delete' => "currenttasks#delete"
  get "/groups/"=> "groups#index"
  get "/users/:user_id/:id/verifY" => "currenttasks#delete"
  get "/users/:user_id/:id/:not" => "currenttasks#delete"
  get "/:user_id/:id/incomplete" => "currenttasks#incomplete"
  get "groups/:group_id/:user_id/leave" => "groups#leave"
  get "groups/:group_id/invite" => "groups#invite"
  post "/groups/:group_id/invitesearch" => "groups#invitesearch"
  resources :invites, :only=> [:destroy]
  get "groups/:group_id/ask" => "groups#ask"
  get "groups/:group_id/:asker_id" => "groups#join"
  resources :asks, :only=> [:destroy]
  post "/groups/search" => "groups#search"
  

  

end

app/models/acceptedtask.rb
class Acceptedtask < ActiveRecord::Base
	belongs_to :user
end

app/models/ask.rb
class Ask < ActiveRecord::Base
	belongs_to :user
end

app/models/completedtask.rb
class Completedtask < ActiveRecord::Base
	belongs_to :user
end

app/models/currenttask.rb
class Currenttask < ActiveRecord::Base
	belongs_to :user

	def verified?
		self.verifed>0
	end
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/incompletetask.rb
class Incompletetask < ActiveRecord::Base
	belongs_to :user
end

app/models/invite.rb
class Invite < ActiveRecord::Base
	belongs_to :user
end

app/models/no.rb
class No < ActiveRecord::Base
	belongs_to :pendingtask
	belongs_to :user
end

app/models/nod.rb
class Nod < ActiveRecord::Base
	belongs_to :pendingtask
	belongs_to :user
end

app/models/pendingtask.rb
class Pendingtask < ActiveRecord::Base
	has_and_belongs_to_many :users
	validates :assignee_id, :text, presence: true
	has_many :pendingvotes
	has_many :nods
	has_many :nos
end

app/models/pendingvote.rb
class Pendingvote < ActiveRecord::Base
	belongs_to :pendingtask
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
  has_and_belongs_to_many :pendingtasks
  has_many :acceptedtasks
  has_many :currenttasks
  has_many :completedtasks
  has_and_belongs_to_many :groups
  has_many :nods
  has_many :nos
  has_many :incompletetasks
  has_many :invites
  has_many :asks
  
	def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.password="cat"
      user.password_confirmation="cat"
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def self.addpending(id, pendingtask)
    User.find_by_id(id).pendingtasks.create!(pendingtask)
  end


end

app/models/yes.rb
class Yes < ActiveRecord::Base
	belongs_to :pendingtask
	
end

app/helpers/application_helper.rb
module ApplicationHelper
	def selectmax(pendingtasks,acceptedtasks,completedtasks,currenttasks,incompletetasks)
      arr=[pendingtasks,acceptedtasks,completedtasks,currenttasks,incompletetasks]
      return arr.max_by {|x| x.size }.size
    end
end

app/helpers/asks_helper.rb
module AsksHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
	def themost(group)
		max=0
		maxuser="bob"
 		group.users.each do |u| 
     		usertotal=0 
     		u.completedtasks.each do |ct|
        		if ct.group == group.name
           			usertotal+=1 if u.id==ct.completer_id
        		end
        	end
        	if usertotal>=max
        		max=usertotal 
        		maxuser=u
        	end
		end
		return maxuser

	end

	def theleast(group)
		min=10000
		minuser=nil
		unless group.users.size==1

 			group.users.each do |u| 
     			usertotal=0 
     			u.completedtasks.each do |ct|
        			if ct.group == group.name
           				usertotal+=1 if u.id==ct.completer_id
        			end
        		end
        		if usertotal<=min
        			min=usertotal 
        			minuser=u
        		end
			end
		end
		return minuser
	end


	def mostrecent(group)
		min=0
		minuser=nil
		minid=-1
 		group.users.each do |u| 
     		usertotal=0 
     		u.completedtasks.each do |ct|
        		if ct.group == group.name

        			if min==0 || ct.created_at > min
    
        				min=ct.created_at
        				minid=ct.id

        				minuser=u

        			end
        		end
        	end
        	answer=[minuser,minid]

        	return answer
		end

		
	end

	def leastrecent(group)
		val=[]
		group.users.each do |u|
			val << u.completedtasks.where(group: group.name).first unless u.completedtasks.where(group: group.name).first==nil
		end


		answer=[val.min_by{ |x| x.id }.user_id, val.min_by{ |x| x.id }]
		return answer
	end

	def never(group)
		val={}
		group.users.each do |u|
			val[u]= u.completedtasks.where(group: group.name).first
		end
		
		answer=val.select{|c| val[c]==nil}

		
		return answer
	end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Roomaker" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    
  <% if current_user %>
 <nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="#"><%= User.find_by_id(current_user).name %></a></h1>
      <!-- goes to their profile page -->
    </li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">

     

        

        <li class="has-dropdown">
        <a href="#">Groups</a>
        <ul class="dropdown">
     
          <li> <%= link_to "New group", "/groups/#{current_user.id}/new" %></li>
           <li><%= link_to "Join group", "/groups" %></li>
        </ul>

      </li>
       <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li class="active"><%= link_to "Task World", user_path(User.find_by_id(current_user)) %></li>
    </ul>
  </section>
</nav>
<% else %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">Roomaker</a></h1>
      <!-- goes to their profile page -->
    </li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">

     
       <li><%= link_to "Sign in", new_session_path %></li>
       
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li><%= link_to "Sign up", new_user_path %></li>
     
    </ul>
  </section>
</nav>
<% if flash[:error] %>

      <%= flash[:error]%>
    <% elsif flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>


<% end %>


    <%= yield %>
    <%= javascript_include_tag "application" %>
<br>
<br>
<br>
    <%= link_to "Home Page", root_url %> 
  </body>
</html>